import { TextInput } from "./fields/textInput.js";
import { EmailInput } from "./fields/emailInput.js";
import { NumberInput } from "./fields/numberInput.js";
import { Toggle } from "./fields/toggle.js";
import { Select } from "./fields/select.js";
import { StringArray } from "./fields/stringArray.js";
import { FormArray } from "./fields/formArray.js";
import { KeyValuePairs } from "./fields/keyValuePairs.js";
import { BooleanCheckbox } from "./fields/boolean.js";
import { DateInput } from "./fields/date.js";
import { Password } from "./fields/password.js";
import { PhoneNumber } from "./fields/phoneNumber.js";
import { Slider } from "./fields/slider.js";
import { FileUpload } from "./fields/fileUpload.js";
import { ColorPicker } from "./fields/colorPicker.js";
import { RichText } from "./fields/richText.js";
import { MultiSelect } from "./fields/multiSelect.js";
import { RadioGroup } from "./fields/radioGroup.js";
import { TimeInput } from "./fields/time.js";
import { DateTimeInput } from "./fields/dateTime.js";
import { Rating } from "./fields/rating.js";
import { JsonEditor } from "./fields/json.js";
import { Tags } from "./fields/tags.js";
import { DiscriminatingForm } from "./fields/discriminatingForm.js";
import { Divider } from "./fields/divider.js";
import { FormContainer } from "./fields/form.js";
import { Section } from "./fields/section.js";
import { TabsFieldComp } from "./fields/tabs.js";
import { InlineGroup } from "./fields/inlineGroup.js";
import { Callout } from "./fields/callout.js";
import { Actions } from "./fields/actions.js";
import { SecretText } from "./fields/secretText.js";
import { CodeEditor } from "./fields/codeEditor.js";
import { Duration } from "./fields/duration.js";
import { Cron } from "./fields/cron.js";
import { IpAllowList } from "./fields/ipAllowList.js";
import { ComboBox } from "./fields/comboBox.js";
import { AsyncSelect } from "./fields/asyncSelect.js";
import { SummaryTable } from "./fields/summaryTable.js";
import { DiffPreview } from "./fields/diffPreview.js";
import { Registry } from "./registryTypes.js";
import { FeatureChecklist } from "./fields/featureChecklist.js";
import { StatusChecklist } from "./fields/statusChecklist.js";
import { ReadOnlyText } from "./fields/readOnlyText.js";
import { ImageUrl } from "./fields/imageUrl.js";

export const registry: Registry = {};

registry.textInput = TextInput;
registry.emailInput = EmailInput;
registry.number = NumberInput;
registry.toggle = Toggle;
registry.select = Select;
registry.stringArray = StringArray;
registry.keyValuePairs = KeyValuePairs;
registry.boolean = BooleanCheckbox;
registry.date = DateInput;
registry.password = Password;
registry.phoneNumber = PhoneNumber;
registry.slider = Slider;
registry.fileUpload = FileUpload;
registry.colorPicker = ColorPicker;
registry.richText = RichText;
registry.multiSelect = MultiSelect;
registry.divider = Divider;
registry.radioGroup = RadioGroup;
registry.time = TimeInput;
registry.dateTime = DateTimeInput;
registry.rating = Rating;
registry.json = JsonEditor;
registry.tags = Tags;
registry.inlineGroup = InlineGroup;
registry.callout = Callout;
registry.actions = Actions;
registry.secretText = SecretText;
registry.codeEditor = CodeEditor;
registry.duration = Duration;
registry.cron = Cron;
registry.ipAllowList = IpAllowList;
registry.comboBox = ComboBox;
registry.featureChecklist = FeatureChecklist;
registry.statusChecklist = StatusChecklist;
registry.readOnlyText = ReadOnlyText;
registry.imageUrl = ImageUrl;
registry.asyncSelect = AsyncSelect;
registry.summaryTable = SummaryTable;
registry.diffPreview = DiffPreview;
registry.section = Section;
registry.form = FormContainer;
registry.formArray = FormArray;
registry.tabs = TabsFieldComp;
registry.discriminatingForm = DiscriminatingForm;
